version: "3"
services:
  rs_node:
    container_name: rs_node
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always